import type { Contact, Quote } from "../src/lib/lead-schema";
export const contact: Contact = {
  kind: "contact",
  requestId: "13621183-3b6b-45ca-9ca0-d99fe7729906",
  name: "Camille Martin",
  email: "camille@example.test",
  company: "Atelier Camille",
  phone: "",
  subject: "Un site pour mon atelier",
  message: "Je souhaite présenter mon activité et mes réalisations.",
  privacy: true,
  fax: "",
};
export const quote: Quote = {
  kind: "quote",
  mode: "express",
  requestId: "dc7469e8-c398-463b-977d-a84a47d214cb",
  name: "Camille Martin",
  email: "camille@example.test",
  company: "Atelier Camille",
  phone: "",
  projectType: "vitrine",
  budget: "2000-4000",
  deadline: "1-3-mois",
  description: "Je souhaite un site pour présenter mon atelier de menuiserie.",
  activity: "",
  audience: "",
  objectives: [],
  existingUrl: "",
  pages: "",
  content: "",
  features: [],
  references: "",
  notes: "",
  privacy: true,
  fax: "",
};
export const fullQuote: Quote = {
  ...quote,
  mode: "complet",
  activity: "Menuiserie sur mesure",
  audience: "Les particuliers du Loiret",
  objectives: ["contacts", "image"],
  pages: "2-5",
  content: "partiel",
  features: ["galerie", "cms"],
  references: "https://example.test — les espaces et les couleurs",
  notes: "Photos disponibles au lancement.",
};
